# Standard workstation intent plus development and extended workstation tools.
#

FORMULAE=(
    gptfdisk
    dockutil
    git
    gh
    jq
    wget
    python
    cmake
    pkg-config
)

CASKS=(
    coteditor
    steam
    tailscale-app
    firefox
    visual-studio-code
    rectangle
    1password
    spotify
    vlc
    keka
    stats
    moonlight
    wireshark-app
    balenaetcher
    private-internet-access
)

# Desired applications requiring Monterey-specific/manual handling.
MANUAL_FORMULAE=(
    ffmpeg
    node
)

MANUAL_APPS=(
    amphetamine
    raspberry-pi-imager
)
