# Essential command-line tools
FORMULAE=(
    gptfdisk
  git
  jq
)

# Essential desktop applications
CASKS=(
    tailscale-app
  firefox
    visual-studio-code
  rectangle
  1password
)

MANUAL_FORMULAE=(ffmpeg)
