# Includes everything in minimal, plus normal daily-use applications.

FORMULAE=(
  git
  gh  jq
  ffmpeg
  yt-dlp
  python
)

CASKS=(
  firefox
  visual-studio-code
  rectangle
  1password
  spotify
  vlc
  keka
  stats
  amphetamine
  moonlight
)
