# Includes everything in minimal, plus normal daily-use applications.

FORMULAE=(
  git
  jq
  ffmpeg
  yt-dlp
)

CASKS=(
  firefox
  google-chrome
  visual-studio-code
  rectangle
  1password
  spotify
  vlc
  keka
  stats
  amphetamine
  moonlight
)
